### ISSUE TITLE
How to compile Fluidsynth 1.17 under Windows?

### ISSUE THREAD

**Issue by YesterPlay80** [FluidSynth/fluidsynth#231] opened 2017-10-09 12:55 UTC
I tried without success to compile the current version of Fluidsynth in Windows. Version 1.16 was only compilable in an older Version of GCC (I used 4.4.0), but at least it worked. All dependencies (pkg-config, glib, gthread, etc.) are available, as they were required by 1.16 already. 

No matter if I try GCC4.4.0 or the currently used GCC6.3.0 in MinGW, I always get the following error:

[ 46%] Building C object src/CMakeFiles/libfluidsynth.dir/rvoice/fluid_rvoice_ev
ent.c.obj
D:\Entwicklung\MINGW\msys\1.0\home\miche\fluidsynth-1.1.7\src\rvoice\fluid_rvoic
e_event.c: In function 'fluid_rvoice_eventhandler_push_LOCAL':
D:\Entwicklung\MINGW\msys\1.0\home\miche\fluidsynth-1.1.7\src\rvoice\fluid_rvoic
e_event.c:186: error: void value not ignored as it ought to be
mingw32-make[2]: *** [src/CMakeFiles/libfluidsynth.dir/rvoice/fluid_rvoice_event
.c.obj] Error 1
mingw32-make[1]: *** [src/CMakeFiles/libfluidsynth.dir/all] Error 2
mingw32-make: *** [all] Error 2

Is there a recommended way to get a working 1.17 build in Windows? Btw, I'm using MinGW+MSYS but used CMAKE to generate the code to compile.

**Comment by derselbst** [comment] 2017-10-09 15:14
Duplicate of #202. Will be fixed in 1.1.8. [See my comment for a solution.](https://github.com/FluidSynth/fluidsynth/issues/202#issuecomment-327404015)

**Comment by ziyamete** [comment] 2017-10-10 10:09
I do not know if it will work for you, but try this:
Directly download the code there: in this page: https://github.com/FluidSynth/fluidsynth
see right side: "clone or download" button.
Otherwise there are a lot of meaningless errors.
After trying many unsuccessful attempts, I wondered it and compiled it as error-free.
Don't ask why. I don't really have an idea on this.

**Closed** 2017-10-13 15:54 UTC
Labels: duplicate
