### ISSUE TITLE
Pausing does not work

### ISSUE THREAD

**Issue by mmehl** [FluidSynth/fluidsynth#1296] opened 2023-12-28 16:12 UTC
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._

FluidSynth runtime version 2.3.3
Copyright (C) 2000-2023 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.3
Sample type=double

### Describe the bug

In EasyABC the libfluidsynth is used to play midi files. Playing works as expected, but pausing and resuming does not work. See https://github.com/jwdj/EasyABC/issues/78#issuecomment-1871037480
The message "fluidsynth: error: The maximum playback duration has been reached. Terminating player!" is shown when restart playing after stopping.

The following extract from a Python program shows the sequence of commands executed which leads to this error:
* start playing the midi file with `fluid_player_play`
* wait a second
* stop playing the midi file with `fluid_player_stop`
* continue playing the midi file with `fluid_player_play`
** at this point the error message is shown in the console, but errcode is "0"

```python
errcode = fluidsynth.fluid_player_add(player, c_char_p(b(midifile)))
if (errcode!=0): logging.warning("add midi failed")

errcode = fluidsynth.fluid_player_seek(player, 0)
if (errcode!=0): logging.warning("seek failed")

errcode = fluidsynth.fluid_player_play(player)
if (errcode!=0): logging.warning("play failed")

time.sleep(1)

errcode = fluidsynth.fluid_player_stop(player)
if (errcode!=0): logging.warning("stop failed")

errcode = fluidsynth.fluid_player_play(player)
if (errcode!=0): logging.warning("continue failed")
```

**Comment by derselbst** [comment] 2023-12-28 17:56
Duplicate of #1272. Use fluidsynth 2.3.4.

**Closed by derselbst** 2023-12-28 17:56 UTC
Labels: bug
