### ISSUE TITLE
Documentation on VLC setup

### ISSUE THREAD

**Issue by nicobrinkkemper** [FluidSynth/fluidsynth#615] opened 2020-01-31 11:11 UTC
I am a simple man. I read docs and follow instructions. VLC docs [right here ](https://wiki.videolan.org/midi) link to sourceforge but if you download that you get a README.md with content: 
``` 
## Active development moved to GitHub.

#### Release notes and future release tarballs can be found there:

https://github.com/FluidSynth/fluidsynth/releases/
```

Honestly. I'm really expecting to read on how to do this when I search the Wiki. Instead I only find a link to VLC, with a description of VLC. In particular, I'm looking for a .sf2 file since that is what the VLC docs talk about. It would really help people that just want to play a midi file.

FYI this is not a how to question, but a request for documentation and/or to fall back in line with the VLC documentation by including a .sf2 file.

EDIT: and for people reading this looking for the file. It's not in the release, but here [https://github.com/FluidSynth/fluidsynth/blob/master/sf2/VintageDreamsWaves-v2.sf2](https://github.com/FluidSynth/fluidsynth/blob/master/sf2/VintageDreamsWaves-v2.sf2)

**Comment by mawe42** [comment] 2020-01-31 11:26
When you look in the fluidsynth wiki on GitHub and see SoundFont anywhere in the text, it is a link. Click on a that link and you come to this page: https://github.com/FluidSynth/fluidsynth/wiki/SoundFont

I must admit I'm not actually sure what the problem is, especially for somebody who actually "reads docs and follows instructions". them Can you maybe make a more concrete suggestion on how to improve the documentation?

**Comment by mawe42** [comment] 2020-01-31 11:32
> EDIT: and for people reading this looking for the file. It's not in the release, but here

And just to make sure people understand: there is no "this file" in FluidSynth. The linked SoundFont is a small font that we use for automated tests. FluidSynth is a synth for generating music via SoundFonts (for example via real-time MIDI  messages, MIDI files or programmatically via the API) but does not come bundled with a particular SoundFont.

Just like VLC does not come bundled with your favourite movie so you can just quickly "get started using VLC".

**Comment by derselbst** [comment] 2020-01-31 14:24
> I must admit I'm not actually sure what the problem is, especially for somebody who actually "reads docs and follows instructions". Can you maybe make a more concrete suggestion on how to improve the documentation?

I second this.

**Comment by nicobrinkkemper** [comment] 2020-01-31 21:31
I read the VLC docs @ the link I mentioned and end up here. VLC also has a settings tab called fluidsynth. I search the WIKI for VLC, no info. Download the release, it's a command-line program. Whole bunch of noise, don't feel like reading everything. I understand it's a lot of work making all this, and I do not wish to offend. I would've just wished there was a small section with a few steps to get midi working on VLC. Just newbe things for people that stumble upon this through the official VLC docs. Anyway thanks for responding

**Comment by derselbst** [comment] 2020-02-01 08:16
> I would've just wished there was a small section with a few steps to get midi working on VLC.

In our wiki? Sry, but it's not our job to document in our wiki how to make fluidsynth work with every possibly existing downstream application. That's the job of the respective application. And I still don't understand what's wrong with the VLC wiki page that you mentioned initially. Exactly this page contains the "few steps to get midi working on VLC" that you are looking for.

**Comment by mawe42** [comment] 2020-02-01 10:53
I think the problem lies in the vlc wiki. The link to fluidsynth is outdated, and they link to us as a source for soundfonts, which is just wrong. We are not a place to get soundfonts. It's like linking to a decoder library they use as a source to get encoded movies.

The vlc wiki is not publicly editable, so I guess it would be best to open an issue with VLC. Ask them to update their outdated wiki page and either remove the link to us or at least point it to the page about soundfonts in our wiki.

**Comment by mawe42** [comment] 2020-02-01 10:57
And just out of curiosity: the first soundfonts source they have is not fluidsynth but Christian Collins site. And it's working and offers immediate downloads of very high quality soundfonts. Why didn't you use those?

**Comment by derselbst** [comment] 2020-02-13 16:19
TO not responding. Closing.

**Closed by derselbst** 2020-02-13 16:19 UTC
Labels: enhancement
