### ISSUE TITLE
multi channel output not working

### ISSUE THREAD

**Issue by mqnc** [FluidSynth/fluidsynth#225] opened 2017-10-04 13:39 UTC
Here is how I run fluidsynth (1.1.6):

`fluidsynth -f fluidsynthcfg.tmp -m jack -a jack -r 44100 -R 0 -C 0 -g 0.5 -j -s -o shell.port=9800 -o midi.jack.id='fluidsynthmidi' -o audio.jack.id='fluidsynthaudio' -o synth.midi-bank-select='mma' -o audio.output-channels=32 -o audio.jack.multi='yes' -o synth.audio-channels=16 -o synth.audio-groups=16`

(the cfg file loads multiple soundfonts)

The fluidsynthaudio client in QjackCtl under Connections -> Audio only has the ports "left" and "right".

I remember that I once got multichannel output working in Qsynth but I don't remember what I did there and I think the midi channels were also not mapped to the audio channels properly.

**Comment by derselbst** [comment] 2017-10-04 13:55
Duplicate of #135

Try again with 1.1.7

**Comment by derselbst** [comment] 2017-10-04 13:58
BTW: Specifies the number of stereo channels so it should be `-o audio.output-channels=16` instead of 32

**Comment by mqnc** [comment] 2017-10-04 15:11
Ok I installed 1.1.7, thanks! It was surprisingly trouble-free-ish.
Now I run

`fluidsynth -f fluidsynthcfg.tmp -m jack -a jack -r 44100 -R 0 -C 0 -g 0.5 -j -s -o shell.port=9800 -o midi.jack.id='fluidsynthmidi' -o audio.jack.id='fluidsynthaudio' -o synth.midi-bank-select='mma' -o audio.output-channels=16 -o audio.jack.multi='yes' -o synth.audio-channels=16 -o synth.audio-groups=16`

and it creates 36 ports as expected. However, it does not route the channels to the respective ports.

If I send notes to an arbitrary midi channel, it is rendered to l_00, r_00 and it is also audible (with lower volume) on channel l_01 (but not on r_01 and also on no other channel).

**Comment by derselbst** [comment] 2017-10-05 08:25
Unfortunately you're right and I'm unable to locate the error :/

**Comment by mawe42** [comment] 2017-10-05 09:55
Just a thought that might help locating the bug: that the output is audible on l_00, r_00 and with lower volume on l_01 and no volume on r_01 could be an indication that l_01 and r_01 are fed from the reverb and chorus effect send channels.

**Comment by derselbst** [comment] 2017-10-05 11:10
> could be an indication that l_01 and r_01 are fed from the reverb and chorus effect send channels.

Sounds dry, not wet. Reverb unlikely. Also I dont think the problem lies in `fluid_synth_nwrite_float()` because it works fine for my own player, so I guess the error must be somewhere in `fluid_jack.c`. I can also reproduce this behavior for 1.1.6, which is strange, because I've tested this in the past with ardour and it worked fine.

**Comment by mawe42** [comment] 2017-10-05 18:34
Correct me if I'm wrong, but "audio.output-channels" never had an effect (at least not in 1.1.6 and 1.1.7) and has since been removed in master.

**Comment by derselbst** [comment] 2017-10-05 18:36
> but "audio.output-channels" never had an effect (at least not in 1.1.6 and 1.1.7) and has since been removed in master.

Correct. Got superseeded by `synth.audio-channels` instead.

**Comment by derselbst** [comment] 2017-10-05 18:44
FOUND IT: When creating the synth and reading out the number of audio-groups, the value retrieved is always 1

https://github.com/FluidSynth/fluidsynth/blob/8d5cccdb80a56091270873194d0ffe826448688c/src/synth/fluid_synth.c#L607

As a consequence the channel mapping gets messed up in `fluid_voice_init()`. Have to investigate why though...

**Comment by mawe42** [comment] 2017-10-05 19:00
It seems like the command-line argument parsing is doing something weird here. Try passing -G 16, then synth->audio_groups is set correctly to 16.

**Comment by derselbst** [comment] 2017-10-05 19:41
Parsing works fine. Actually synth.audio-groups is overwritten some lines later in fluidsynth.c

https://github.com/FluidSynth/fluidsynth/blob/8d5cccdb80a56091270873194d0ffe826448688c/src/fluidsynth.c#L596-L599

Will fix tomorrow.

**Comment by derselbst** [comment] 2017-10-06 09:01
@mqnc The quickest fix for you is to use `-G 16` to specify the number of audio-groups. You could also check out the 1.1.x branch and build it, or wait for 1.1.8

**Closed** 2017-10-06 11:08 UTC
Labels: bug
