### ISSUE TITLE
Glissando control is not working as expected.

### ISSUE THREAD

**Issue by HectorRicardo** [FluidSynth/fluidsynth#682] opened 2020-10-05 04:26 UTC
### FluidSynth version
FluidSynth runtime version 2.1.5

### Describe the bug
The glissando control is not working as expected (controller numbers `65` and `5`). I am on Windows 10, using version 2.1.5's dlls that I downloaded from the release sections.

### Steps to reproduce
Run this sample code (this is an adaptation from the code obtained from http://www.fluidsynth.org/api/example_8c-example.html)

```c
#include <fluidsynth.h>
#if defined(WIN32)
#include <windows.h>
#else
#include <stdlib.h>
#include <unistd.h>
#endif
int main()
{
    fluid_settings_t *settings = new_fluid_settings();
    fluid_synth_t *synth = new_fluid_synth(settings);
    fluid_audio_driver_t *adriver = new_fluid_audio_driver(settings, synth);

    fluid_synth_sfload(synth, "example.sf2", 1);

    // -------------------> These lines are not working as expected.
    fluid_synth_cc(synth, 0, 65, 127); // Turn on glissando
    fluid_synth_cc(synth, 0, 5, 80); // Set glissando level

    fluid_synth_noteon(synth, 0, 60, 127);
    fluid_synth_noteon(synth, 0, 64, 127);
    fluid_synth_noteon(synth, 0, 67, 127);
    Sleep(500);
    fluid_synth_noteoff(synth, 0, 60);
    fluid_synth_noteoff(synth, 0, 127);
    fluid_synth_noteoff(synth, 0, 67);

    fluid_synth_noteon(synth, 0, 62, 127);
    fluid_synth_noteon(synth, 0, 65, 127);
    fluid_synth_noteon(synth, 0, 69, 127);
    Sleep(500);
    fluid_synth_noteoff(synth, 0, 62);
    fluid_synth_noteoff(synth, 0, 65);
    fluid_synth_noteoff(synth, 0, 69);

    fluid_synth_noteon(synth, 0, 64, 127);
    fluid_synth_noteon(synth, 0, 67, 127);
    fluid_synth_noteon(synth, 0, 71, 127);
    Sleep(500);
    fluid_synth_noteoff(synth, 0, 127);
    fluid_synth_noteoff(synth, 0, 67);
    fluid_synth_noteoff(synth, 0, 71);

    delete_fluid_audio_driver(adriver);
    delete_fluid_synth(synth);
    delete_fluid_settings(settings);
    return 0;
}
```

I listen to the sound produced by this code. Then, I compare it with the following code, which is the equivalent as the above, except that it's using the Java built-in synthesizer (Gervill).

```java
import java.io.File;
import java.io.IOException;

import javax.sound.midi.Instrument;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiChannel;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.Patch;
import javax.sound.midi.Soundbank;
import javax.sound.midi.Synthesizer;

public class HelloWorld {
  public static void main(String[] args) throws MidiUnavailableException, InterruptedException, InvalidMidiDataException, IOException {
    Soundbank soundbank = MidiSystem.getSoundbank(new File("example.sf2"));
    Instrument instrument = soundbank.getInstrument(new Patch(0, 0));

    Synthesizer synthesizer = MidiSystem.getSynthesizer();
    synthesizer.open();

    synthesizer.unloadAllInstruments(synthesizer.getDefaultSoundbank());
    synthesizer.loadInstrument(instrument);

    MidiChannel channel = synthesizer.getChannels()[0];

    channel.programChange(0, 0);

    // -------------------> In contrast, these lines are working as expected
    channel.controlChange(65, 127);
    channel.controlChange(5, 80);

    channel.noteOn(60, 64);
    channel.noteOn(64, 64);
    channel.noteOn(67, 64);
    Thread.sleep(500);
    channel.noteOff(60);
    channel.noteOff(64);
    channel.noteOff(67);

    channel.noteOn(62, 64);
    channel.noteOn(65, 64);
    channel.noteOn(69, 64);
    Thread.sleep(500);
    channel.noteOff(62);
    channel.noteOff(65);
    channel.noteOff(69);

    channel.noteOn(64, 64);
    channel.noteOn(67, 64);
    channel.noteOn(71, 64);
    Thread.sleep(500);
    channel.noteOff(64);
    channel.noteOff(67);
    channel.noteOff(71);

    synthesizer.close();
  }
}
```

With the Java synthesizer, I can definitely hear the glissando effect clearly. I would expect to here the same effect with FluidSynth. 

### Additional context
I attached the .sf2 soundfont file used in the sample code above.
soundfont.zip

[soundfont.zip](https://github.com/FluidSynth/fluidsynth/files/5325216/soundfont.zip)

**Comment by derselbst** [comment] 2020-10-05 17:13
Frankly, it is not clear to me why this is a bug, just because your expectations weren't met. I never used portamento myself, but I know it is supported and perhaps @jjceresa might be able to tell you directly what you did wrong. In the meantime, please [read our documentation](https://github.com/FluidSynth/fluidsynth/wiki/FluidFeatures) and check out the [legato/portamento example scripts](https://github.com/FluidSynth/fluidsynth/tree/master/doc/polymono) that can be used with fluidsynth's command shell.

**Comment by jjceresa** [comment] 2020-10-05 18:17
I have tested example.sf2 using the fluidsynth application console.

#run fluidsynth with the `example.sf2` soundfont.
>fluidsynth example.sf2

#Then, set program change preset 0 to MIDI channel 0 (**Note this is missed in your c example compared to java example !!**)
>prog 0 0

#Then set portamento on on channel 0
>cc 0 65 127
#Then set MSB portamento time between note (on channel 0). I choose 2 (254 ms) rather then 5 (635 ms) 
>cc 0 5 2    

# then play some notes C4, E4, C4, of course still on channel 0
>noteon 0 60  127
>noteon 0 64  127  # we hear the rising portamento from C4 to E4
>noteon 0 60  127 #  we hear the falling portamento from E4 to C4 

Note that actually channel 0 is polyphonic, so you hear a portamento effect on an instrument (piano) that is played polyphonic. This is not very natural. Of course, it will be better to play this on a channel set to monophonic and using an instrument naturally monophonic (i.e oboe, flute, clarinet,..) 




Assuming Java built-in synthesizer (Gervill) is making use of Fluidsynth, it seems that both example aren't not

**Comment by jjceresa** [comment] 2020-10-05 18:35
Sorry for the bad formatting of previous comment, and incomplete last sentence.

Assuming Java built-in synthesizer (Gervill) is making use of Fluidsynth, it seems that both examples aren't not equivalent.

If you intend to make things equivalent,  please instead of fluid_synth_sfload(synth, "example.sf2", 1), try this.
fluid_synth_program_select_by_sfont_name(synth,  0, "example.sf2", 0, 0 )

Also,  replace any **fluid_synth_noteoff(synth, 0, 127)** by `fluid_synth_noteoff(synth, 0, 64)` (though it is not important as this doesn't impact portamento behaviour).

**Comment by jjceresa** [comment] 2020-10-05 18:39
Sorry for the bad formatting of previous comment, and incomplete last sentence.

Assuming Java built-in synthesizer (Gervill) is making use of Fluidsynth, it seems that both examples aren't not equivalent.

If you intend to make things equivalent,  please instead of fluid_synth_sfload(synth, "example.sf2", 1), try this.
fluid_synth_program_select_by_sfont_name(synth,  0, "example.sf2", 0, 0 )

Also,  replace any **fluid_synth_noteoff(synth, 0, 127)** by `fluid_synth_noteoff(synth, 0, 64)` (though it is not important as this doesn't impact portamento behaviour).

**Comment by jjceresa** [comment] 2020-10-05 18:45
>Assuming Java built-in synthesizer (Gervill) is making use of Fluidsynth

Does any one know if Java built-in synthesizer (Gervill) is making use of Fluidsynth library ?

**Comment by jjceresa** [comment] 2020-10-05 20:00
I think, I  understand why you don't hear portamento sweep in your C example using fluidsynth.

`fluid_synth_cc(synth, 0, 5, 80); // Set glissando level`

This set 80 in MSB portamento time. In fluidsynth, portamento time is a 14 bit value with a resolution of 1 ms.
This leads in a portamento duration of : MSB x 127 = 80 x 127 = 10160 ms, which means that playing C4 followed by E4, the pitch of C4 will take 10 second to reach E4. As in the C example the note duration is only 0.5 second, we hear a very small pitch sweep.

1)In C example try to replace 80 by 2 (254 ms), and you should be able to hear a more perceptible portamento.
2) In your both examples (c,java) make use of delay between noteon.
3) If both synthesizer are different in each example:
    - it is likely that java synth considers portamento time only on 7 bits value.
    - also what could be the time resolution in java synthesizer ?

**Comment by derselbst** [comment] 2020-10-06 16:18
> This set 80 in MSB portamento time. In fluidsynth, portamento time is a 14 bit value with a resolution of 1 ms.

Thank you @jjceresa. I can confirm that this solves this issue. I've updated the wiki page to emphasize this point.

> Does any one know if Java built-in synthesizer (Gervill) is making use of Fluidsynth library ?
> it is likely that java synth considers portamento time only on 7 bits value.
> also what could be the time resolution in java synthesizer ?

It doesn't. It's a reinvention of the wheel written in Java. Source code is available here: https://github.com/bluenote10/gervill

Closing this as not a bug.

**Closed by derselbst** 2020-10-06 16:18 UTC
Labels: bug

**Comment by jjceresa** [comment] 2020-10-06 22:01
>In fluidsynth, portamento time is a 14 bit value with a resolution of 1 ms.

Portamento time (5d,37d) is fully documented in FluidPolyMono-0004.pdf chapter 3.8.5. The default value is  0 which means that no portamento sweep is perceptible (even if portamento pedal (65d) is on). This zero default value is deliberated to get the user compelled to set portamento time value according to its need.

>I've updated the wiki page to emphasize this point.

Thank you.
