### ISSUE TITLE
macOS Catalina and fluidsynth 2.0.8 causes segmentation fault

### ISSUE THREAD

**Issue by micaharvey** [FluidSynth/fluidsynth#595] opened 2019-12-02 02:56 UTC
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._

`fluidsynth --version`
```
FluidSynth runtime version 2.0.8
Copyright (C) 2000-2019 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

FluidSynth executable version 2.0.8
Sample type=double
```

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._

Running fluidsynth on macOS Catalina `10.15.1`and fluidsynth version `2.0.8` causes segmentation fault.

### Expected behavior
_Provide a clear and concise description of what you expected to happen._

fluidsynth should be able to run without segmentation fault from cli and when using the library.

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._

I followed the steps at
https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-on-os-x
to run
`brew install fluidsynth pkg-config`
and things seem to install okay.  Using fluidsynth on the command line or using it in my programs as a library causes a segmentation fault.

My other mac laptop is on macOS Mojave Version `10.14.6` and fluidsynth version `1.1.11`.  This runs great and I can use the library for writing code by including `pkg-config fluidsynth --libs` in my compile command.  Hoping to get the latest working as well.

I wonder if this has to do with the latest mac version? Or perhaps a wider spread issue with fluidsynth v2.0.8?  I figured this is of importance as this is the main suggested way to install fluidsynth to macOS and results in an unusable program.

### Additional context
_If you are able to illustrate the bug with an example, please provide simple
source code below or as attached file. List any other information that is relevant to your issue, e.g. stack traces, related issues, build logs, suggestions on how to fix, links to related discussions at fluid-dev, etc._

Example output from running
`fluidsynth /Users/path/to/Masterpiece.sf2 /Users/path/to/cs1-1pre.mid`
```
FluidSynth runtime version 2.0.8
Copyright (C) 2000-2019 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

Segmentation fault: 11
```

**Comment by derselbst** [comment] 2019-12-02 05:10
Duplicate of #591.

Use fluidsynth 2.0.9 or 2.1.0 .

**Closed by derselbst** 2019-12-02 05:10 UTC
Labels: bug, duplicate

**Comment by micaharvey** [comment] 2019-12-02 05:29
Thanks @derselbst :)

Wish I had searched the other bugs first, only saw the 12 open issues.  

In this case I will give the newer code a go.  Will 2.0.9 or 2.1.0 be heading to homebrew soon?

**Comment by micaharvey** [comment] 2019-12-02 06:21
Updating to 2.1.0 did indeed fix using fluidsynth from the terminal.  However, I'm having some trouble building and installing the dev library using cmake.  I thought using `make all` and then `sudo make install` would generate and install the libraries, but pkg-config cannot find them when the time comes to compile this error appears:
```
Package fluidsynth was not found in the pkg-config search path.
Perhaps you should add the directory containing `fluidsynth.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fluidsynth' found
my-program.c:18:10: fatal error: 'fluidsynth.h' file not found
#include <fluidsynth.h>
```
I tried adding the build folder to PKG_CONFIG_PATH, but this didn't accomplish much.
Any tips?

**Comment by derselbst** [comment] 2019-12-02 07:57
> I tried adding the build folder to PKG_CONFIG_PATH, but this didn't accomplish much.

Add that folder into which fluidsynth.pc was installed.

Otherwise, try:

![image](https://user-images.githubusercontent.com/8152480/69939676-c7784800-14e0-11ea-871f-d7a1767c3287.png)

**Comment by micaharvey** [comment] 2019-12-03 20:55
I found the appropriate `fluidsynth.pc` was installed at `/usr/local/lib64/pkgconfig/fluidsynth.pc` and once I added that to the `PKG_CONFIG_PATH`, the warning went away meaning the package is now found.  Nice.  But when I go to include <fluidsynth.h> I still get
```
terminal-hero.c:18:10: fatal error: 'fluidsynth.h' file not found
#include <fluidsynth.h>
         ^~~~~~~~~~~~~~
1 error generated.
```
Wondering how I can resolve this.  Also wondering when the homebrew version of fluidsynth might get bumped.  Thanks!
