### ISSUE TITLE
Incorrect playback of descent12.mid compared to TiMidity++

### ISSUE THREAD

**Issue by iskunk** [FluidSynth/fluidsynth#1311] opened 2024-03-29 03:09 UTC
### FluidSynth version
I verified the issue with a build of the Git tree, commit `db86c36b`.
```
$ ./fluidsynth --version
FluidSynth runtime version 2.3.5
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.5
Sample type=double
```

### Describe the bug
Playback of `descent12.mid`, a General MIDI file ripped from the old *Descent* PC game, is incorrect compared to TiMidity++.

Here is a zip file containing the MIDI at issue, and Ogg Vorbis conversions of a portion of the WAV output from TiMidity++ and FluidSynth: [fluidsynth-bug-files.zip](https://github.com/FluidSynth/fluidsynth/files/14798600/fluidsynth-bug-files.zip)

At about the 17-second mark, a strong synthetic horn (?) section begins playing. The TiMidity++ rendition sounds correct; it's how I've always heard this piece. FluidSynth, on the other hand, renders it in a most amusingly wrong way.

(If it matters, I used the `8mbgmsfx.sf2` soundfont to render this MIDI file.)

### Expected behavior
The horns should sound like the TiMidity++ rendition, not like... *that*.

### Steps to reproduce
These are the commands I used to produce the WAV file outputs. No user config files were present:
```
$ timidity -x'soundfont 8mbgmsfx.sf2 order=0' -Ow descent12.mid

$ ./fluidsynth -a file -i -n 8mbgmsfx.sf2 descent12.mid
```

### Additional context
I first encountered this bug via the AMIDI-Plug plug-in for the Audacious music player, but quickly tracked it down to the FluidSynth backend.

**Comment by derselbst** [comment] 2024-03-29 17:34
Duplicate of https://github.com/FluidSynth/fluidsynth/issues/705#issuecomment-731748590 and of #1232

Since this is already the third time someone is running into this, I once again want to emphasize that I'm generally open for changing this or even better, making the range for the portamento time customizable as I've explained here: https://github.com/FluidSynth/fluidsynth/issues/705#issuecomment-1657165588

If anybody is willing to invest time for this, pls. create a discussion before filing any PR, as the solution space is quite big.

**Closed by derselbst** 2024-03-29 17:34 UTC
Labels: bug, duplicate
