### ISSUE TITLE
I hear a crackle sound

### ISSUE THREAD

**Issue by Toadfield** [FluidSynth/fluidsynth#918] opened 2021-06-18 23:26 UTC
### FluidSynth version
I use fluidsynth 2.1.8-1.

### Describe the bug
When I start fluidsynth then I hear some strangle crackle sounds,even if no midi music is playing.

### Expected behavior
That I don't hear those sounds.

### Steps to reproduce
1. Install fluidsynth from the arch repo
2. Install qsynth from the arch repo
3. Install soundfont-fluid
3. Start qsynth
4. Select "Alsa_seq" as audio device
5. Select "/usr/share/soundfonts/FluidR3_GM.sf2" or "/usr/share/soundfonts/FluidR3_GS.sf2" as soundfont
6. Start qsynth
7. Start a midi game

### Additional context
I use qsynth,cause I am too dumb for the terminal.
I use Arch Kde.

**Comment by derselbst** [comment] 2021-06-19 08:54
This can happen when you use ALSA as audio driver (Alsa_seq is the midi device). It's not quite clear why this happens. It heavily depends on the system, the soundcard, the CPU load of the OS and whether or not fluidsynth has permission to set the synth thread to realtime mode (you should see a warning in case). Either use a different audio driver or try to increase the period-size and the number of periods (audio-buffers).

**Comment by Toadfield** [comment] 2021-06-19 22:43
This is my system information if it helps:
![image](https://user-images.githubusercontent.com/68649672/122655645-4c26c780-d154-11eb-824e-cd019a40bb37.png)
So is there any workaround for this?
Which audio driver should I select so it works?

**Comment by Toadfield** [comment] 2021-06-20 01:57
When I set the audio driver to pulseaudio,then this bug also happens.

**Comment by derselbst** [comment] 2021-07-17 08:54
I have no further advice beyond what I've already said. And since I cannot reproduce it, I'm closing this.

**Closed by derselbst** 2021-07-17 08:54 UTC
Labels: bug

**Comment by tvandorffy** [comment] 2022-11-01 16:54
Hi,

I have the very same problem with fluidsynth 2.3.0.
I am using MX Linux MX-21.2.1
My system uses pulseaudio. Fluidsynth produces the same symptoms.
If I use sdl2 as my sound driver (-a sdl2), the sound is clear as crystal.
My question: is it possible to set this sound driver as default for fluidsynth somehow?
(I am thinking about a config file somewhere)
I have found the config file /etc/default/fluidsynth but changing that does not seem to have any effect.
I have read somewhere that this config file is for server mode.
I was also thinking to compile fluidsynth from source and disabling pulseaudio and enabling sdl2 but I am struggling to find the right command to do that.

Any help is appreciated!
