### ISSUE TITLE
Strange off-tune portamento

### ISSUE THREAD

**Issue by KyleJ61782** [FluidSynth/fluidsynth#1232] opened 2023-04-07 16:43 UTC
### FluidSynth version
FluidSynth runtime version 2.3.2
Copyright (C) 2000-2023 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.2
Sample type=float

### Describe the bug
When playing Game08.mid from the retro game Descent, track 8 plays a sawtooth wave on channel 5 with portamento. On FluidSynth, the instrument goes strangely off key throughout the sequence. When played with the portamento disabled on channel 5 and when played using an SC-8820 or using BassMidi, the portamento doesn't result in such strange dissonant tones.

### Expected behavior
It should be closer to the BassMidi output.

### Steps to reproduce
Play Game08.mid. The Fluid R3 soundfont makes it painfully objvious.

### Additional context
Recording of what it sounds like with portamento [https://drive.google.com/file/d/171h5Rw1DpnDDHqql0ZxPdbltPTiwXbH8/view?usp=share_link](https://drive.google.com/file/d/171h5Rw1DpnDDHqql0ZxPdbltPTiwXbH8/view?usp=share_link)
Recording with portamento disabled: [https://drive.google.com/file/d/16xmfLkO1HtyTp6qj0f_OYpYfZVSYiLCe/view?usp=share_link](https://drive.google.com/file/d/16xmfLkO1HtyTp6qj0f_OYpYfZVSYiLCe/view?usp=share_link)
Recording using BassMidi: [https://drive.google.com/file/d/170xi-kHXCypR_fYRkUxBGk188b5u6QwI/view?usp=share_link](https://drive.google.com/file/d/170xi-kHXCypR_fYRkUxBGk188b5u6QwI/view?usp=share_link)
Original midi with portamento: [https://drive.google.com/file/d/17AGZBZGjNNz6FmKspK2Fru1qBi8bosVK/view?usp=share_link](https://drive.google.com/file/d/17AGZBZGjNNz6FmKspK2Fru1qBi8bosVK/view?usp=share_link)

**Comment by derselbst** [comment] 2023-04-07 17:28
Duplicate of https://github.com/FluidSynth/fluidsynth/issues/705#issuecomment-731748590

**Closed by derselbst** 2023-04-07 17:28 UTC
Labels: bug, duplicate
