### ISSUE TITLE
Android :(    cannot locate symbol "in6addr_any"   

### ISSUE THREAD

**Issue by KingZD** [FluidSynth/fluidsynth#753] opened 2021-01-25 03:12 UTC
### FluidSynth version
2.1.5

### Describe the bug
when i run fluidsynth in android 6 （ps: sorry，  my english is bad  😹） 
```
01-25 10:06:26.434 29567-29567/com.example.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.demo, PID: 29567
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "/data/app/robkoo.example.demo-2/lib/arm64/libfluidsynth.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.example.demo.Synthesizer.<init>(Synthesizer.kt:9)
        at com.example.demo.Synthesizer$Companion.getSyn(Synthesizer.kt:21)
        at com.example.demo.MidiClient.<init>(MidiClient.kt:20)
        at f.l.d.o.a.onCreate(AbstractBleMidiService.kt:52)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3092)
        at android.app.ActivityThread.access$2100(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1600)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
```

### Expected behavior
thanks, i hope fluidsyhtn good running on android 6, 

### Steps to reproduce
i use [circleci](https://app.circleci.com/pipelines/github/FluidSynth/fluidsynth) to build master branch

### Additional context
[file](https://github.com/KingZD/repo/raw/master/fluidsynth_2.1.5/lib.zip)

**Comment by derselbst** [comment] 2021-01-25 09:13
Duplicate of https://lists.nongnu.org/archive/html/fluid-dev/2020-11/msg00000.html

The fluidsynth android binaries were built against Android API 29 using the NDK r18b. They are not supported on older Android versions.

**Closed by derselbst** 2021-01-25 09:13 UTC
Labels: bug, duplicate, invalid
