### ISSUE TITLE
building the Windows binary

### ISSUE THREAD

**Issue by BrannonKing** [FluidSynth/fluidsynth#191] opened 2017-08-16 16:05 UTC
This tool has again become difficult to build on Windows. The glib dependencies for Windows are no longer downloadable in any form other than MSYS2 packages. The use of `check_include_file` makes the CMakeLists.txt incompatible with mingw-w64; hence, I can't cross compile it from Linux either. Please make this process easier or check in a Windows EXE (which is allowed on GitHub, or you could use their "releases" feature).

**Comment by derselbst** [comment] 2017-08-16 16:54
I would first like to understand what the root cause of your problem is: the glib dependency or `check_include_file`?

> The glib dependencies for Windows are no longer downloadable in any form other than MSYS2 packages.

Couldnt you build it yourself? Just asking... I'm a Linux user. Not sure how other windows users cope with this. Maybe @harborsiem can give some input?

> or check in a Windows EXE

No. I absolutely dislike filling a repository with a bunch of binaries. This would just be a way of coping with the symptoms instead of tackling the cause. Also if we would start checking in an EXE, other users will come asking for a static Linux or MacOSX or OS/2 lib for all the various architectures out there. Where would one draw a line, saying these binaries we DO check in but those we do NOT?

**Comment by BrannonKing** [comment] 2017-08-16 18:11
I would be satisfied if we could cross-compile from Linux. That fails with the error below.

I would also be satisfied if I could use cmake on Windows. I have VS2017 and CMake 3.9 installed on Windows. I run that cmake on fluidsynth, and I'm immediately met with a "pkg-config is required" error. Looking at the CMakeLists.txt, I see that it wants it to find glib and a bunch of other packages. Okay, I'll go get it. An hour later and I haven't found anyone online who has it pkg-config or glib except MSYS2. I have used MSYS2 before; I need it once every 18 months to compile package on Windows. It sounds like that's what I'll be installing and reviewing tonight. In other news, pkg-config is on its way out. CMake's find_package is much preferred...

When attempting to cross compile from Linux, I get this error:
```
In file included from /usr/include/glib-2.0/glib/gtypes.h:35:0,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/brannon/fluidsynth/fluidsynth/src/utils/fluidsynth_priv.h:25,
                 from /home/brannon/fluidsynth/fluidsynth/src/bindings/fluid_rtkit.c:28:
/usr/include/time.h:75:18: error: conflicting types for ‘time_t’
 typedef __time_t time_t;
                  ^
In file included from /usr/share/mingw-w64/include/stddef.h:7:0,
                 from /usr/lib/gcc/x86_64-w64-mingw32/5.3-win32/include/stddef.h:1,
                 from /usr/include/glib-2.0/glib/gmacros.h:38,
                 from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/brannon/fluidsynth/fluidsynth/src/utils/fluidsynth_priv.h:25,
                 from /home/brannon/fluidsynth/fluidsynth/src/bindings/fluid_rtkit.c:28:
/usr/share/mingw-w64/include/crtdefs.h:138:20: note: previous declaration of ‘time_t’ was here
 typedef __time64_t time_t;
```

Obviously we don't want to include `/usr/include` while cross-compiling. All includes should come from `/usr/share/mingw-w64/include`. However, the current cmake support is pretty aggressive on locating its own include files.

**Comment by derselbst** [comment] 2017-08-16 19:22
> I have VS2017 and CMake 3.9 installed on Windows. I run that cmake on fluidsynth, and I'm immediately met with a "pkg-config is required" error.

I see. Have a look how [this commit](https://github.com/quiasmo/fluidsynth/commit/bb089dfdb0456c521f47b45b68572c6dbef7771b) approaches this issue. If it's useful I can integrate it.

> In other news, pkg-config is on its way out.

Dont quite aggree on that. At least on linux (or unix in general?) it's a pretty straightforward approach to use .pc files that were shipped with libraries to easily locate, compile and link against these libs, since not every library/package is natively supported by cmakes `find_package`.

**Comment by BrannonKing** [comment] 2017-08-17 03:31
I went down the road mentioned in your linked commit.

1. I downloaded glib from here: https://download.gnome.org/binaries/win64/
2. I modified config_win32.cmake to remove snprintf, which seems to be defined in present libs.
3. I modified the CMakeLists.txt to include the snippet below.
3. I ran cmake from my parent fluidsynth folder from a VS2017 x64 cmd prompt: "C:\Program Files\CMake\bin\cmake.exe" fluidsynth/ -DCMAKE_BUILD_TYPE=Release -CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
3. The build failed so I had to fix all the `machine:X86" -> X64 in the vcxproj files.
4. I then ran msbuild FluidSynth.sln /p:Configuration=Release /p:Platform=x64 and the file built successfully.
5. Alas, it doesn't run, even with the lib files in the path. Error: The application was unable to start correctly (0xc000007b).

Snippet:
```
if ( WIN32 )

  FIND_LIBRARY( GLIB_LIB glib-2.0 PATH "/Utils/glib-dev_2.26.1-1_win64/lib" NO_DEFAULT_PATH )
  FIND_LIBRARY( GLIB_GTHREAD_LIB gthread-2.0 PATH "/Utils/glib-dev_2.26.1-1_win64/lib" NO_DEFAULT_PATH )
  FIND_PATH( GLIB_GLIBH_DIR glib.h PATH "/Utils/glib-dev_2.26.1-1_win64/include" PATH_SUFFIXES "glib-2.0" NO_DEFAULT_PATH  )
  FIND_PATH( GLIB_GLIBCONF_DIR glibconfig.h PATH "/Utils/glib-dev_2.26.1-1_win64/lib/glib-2.0/include"  NO_DEFAULT_PATH  )
  
  IF( GLIB_LIB MATCHES "GLIB_LIB-NOTFOUND" OR
  	GLIB_GTHREAD_LIB MATCHES "GLIB_GTHREAD_LIB-NOTFOUND" OR
  	GLIB_GLIBH_DIR MATCHES "GLIB_GLIBH_DIR-NOTFOUND" OR
  	GLIB_GLIBCONF_DIR MATCHES "GLIB_GLIBCONF_DIR-NOTFOUND")
  	message( WARNING "Unable to locate GLIB for Windows. Proceeding regardless...")
  ENDIF()
  
  SET ( GLIB_LIBRARIES ${GLIB_LIB} ${GLIB_GTHREAD_LIB} )
  SET ( GLIB_INCLUDE_DIRS ${GLIB_GLIBH_DIR} ${GLIB_GLIBCONF_DIR} )
  
  message( STATUS "GLIB_LIBRARIES: " ${GLIB_LIBRARIES} )
  message( STATUS "GLIB_INCLUDE_DIRS: " ${GLIB_INCLUDE_DIRS} )

else () do pkg-config stuff...
```

**Comment by derselbst** [comment] 2017-08-17 08:41
Hard to tell what's wrong, some guesses:
* You seem to have linked against glib `.lib` files? How about linking against the `.dll`?
* Would changing the [Run-Time Library](https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx) make any difference?
* Have you tried running the executable as admin?

**Comment by harborsiem** [comment] 2017-08-17 11:36
I have build fluidsynth version 1.1.6 with VS 2017 for the x86 platform (only with the changes for snprintf). It is working in an application. In the binary path of the application there must be libfluidsynth.dll, libglib-2.0-0.dll and libgthread-2.0-0.dll.
You can check dependency of dlls with a tool called “depends.exe”. It has x86 and x64 support.

http://www.dependencywalker.com/

**Comment by harborsiem** [comment] 2017-08-17 13:45
Important: You also need the intl.dll in the application directory.

**Comment by BrannonKing** [comment] 2017-08-23 00:16
When I attempt to build using MSYS2 (after installing necessary packages and excluding readline from CMakeLists.txt because of unresolved cmake globals), I received this error and many other similar ones during compilation:

```
(ClCompile target) ->
  c:\workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2146: syntax error: missing ')' before identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  c:\workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2061: syntax error: identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  c:\workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2059: syntax error: ';' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  c:\workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2059: syntax error: ',' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  c:\workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2059: syntax error: ')' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(357): error C2146: syntax error: missing ')' before identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(357): error C2081: 'pid_t': name in formal parameter list illegal [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(357): error C2061: syntax error: identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(357): error C2059: syntax error: ';' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(357): error C2059: syntax error: ',' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(357): error C2059: syntax error: ')' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(361): error C2146: syntax error: missing ')' before identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(361): error C2081: 'pid_t': name in formal parameter list illegal [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(361): error C2061: syntax error: identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(361): error C2059: syntax error: ';' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(361): error C2059: syntax error: ',' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(361): error C2059: syntax error: ')' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(377): error C2146: syntax error: missing ')' before identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(377): error C2061: syntax error: identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(377): error C2059: syntax error: ';' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(377): error C2059: syntax error: ',' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.c(377): error C2059: syntax error: ')' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\drivers\fluid_oss.c(35): fatal error C1083: Cannot open include file: 'sys/soundcard.h': No such file or directory [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2146: syntax error: missing ')' before identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2061: syntax error: identifier 'thread' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2059: syntax error: ';' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2059: syntax error: ',' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
  C:\Workspace\fluidsynth\fluidsynth\src\bindings\fluid_rtkit.h(52): error C2059: syntax error: ')' [C:\Workspace\fluidsynth\build\src\libfluidsynth.vcxproj]
```

It's probably a GCC 7 feature to use the word "thread" as a keyword or something similar. Has this tool ever been compiled with GCC 7.2?

**Comment by derselbst** [comment] 2017-08-23 09:25
> Has this tool ever been compiled with GCC 7.2?

gcc 7.2 was just released a week ago, so no. Also the error messages look like MSVC rather than gcc.

Anyway, `fluid_rtkit.c` is only needed when you want to support dbus. Try running cmake again setting the `enable-dbus` variable to FALSE:

```
cmake  -Denable-dbus=0 .
```

But how did you convince cmake to build the OSS audio driver (`fluid_oss.c`) on windows?! What packages did you install specifically? Could you post the output of the cmake during configuration?

**Comment by RyanBram** [comment] 2017-09-17 14:08
Is it possible for FluidSynth to adopt some changes from [FluidLite](https://github.com/divideconcept/FluidLite) or [Fluidsynth-lite](https://github.com/dotfloat/fluidsynth-lite) to make FluidSynth less heavy?

**Comment by derselbst** [comment] 2017-09-17 15:09
Stripping away code like the two forks did is not an option. If you're having some specific change in mind we may talk about that.

**Comment by derselbst** [comment] 2017-10-19 18:00
Thread opener not responding for 2 months. Closing.

**Closed by derselbst** 2017-10-19 18:00 UTC
