### ISSUE TITLE
[BUG] Saw Lead is played out of tune

### ISSUE THREAD

**Issue by spessasus** [FluidSynth/fluidsynth#1456] opened 2024-12-23 17:10 UTC
### FluidSynth version
```
FluidSynth runtime version 2.4.1
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.4.1
Sample type=double
```

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._
[The archive](https://files.catbox.moe/hrlazr.zip) contains a midi file, and a rendition of it using GeneralUserGS 2.0.1.

Around `00:20`, a saw lead comes in which is detuned in fluidsynth, but not in spessasynth. I'm not sure what kind of problem is it, with midi player or with the synth itself. Either way it sounds strange.

### Expected behavior
_Provide a clear and concise description of what you expected to happen._
It should sound like spessasynth. (BASSMIDI also works fine, so I know that fluid is the odd one here.)

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._
1. `fluidsynth GeneralUser-GS.sf2 1TOWOW.mid -F out.wav`
2. listen

**Comment by ReinholdH** [comment] 2024-12-24 07:41
My 2 cents:
The de-tuning happens at 00:28 where the notes of A3 and C4 slightly overlap. I created a simple MIDI file with just A3, C4 fully overlapping and the same controller events, program change etc. as in the sample 1TOWOW.MID
(see [1TOWOW_reduced_to_A3_C4.zip](https://github.com/user-attachments/files/18237121/1TOWOW_reduced_to_A3_C4.zip)).
In my opinion it turns out that the controller event 5 (PORTAMENTO_TIME_MSB) = 8 causes the de-tuning. With PORTAMENTO_TIME_MSB = 0 there is no de-tuning.

**Comment by derselbst** [comment] 2024-12-27 11:02
Duplicate of #1311, #1232, #705.

This is caused by Portamento, Reinhold is correct. I'll add the MIDIs to our testsuite. Yet, it works as designed, PortamentoTime is 14bit wide with a resultion of 1ms. See my comment here https://github.com/FluidSynth/fluidsynth/issues/1311#issuecomment-2027529974

**Closed by derselbst** 2024-12-27 11:02 UTC
Labels: bug, duplicate
