### ISSUE TITLE
Bug when playing notes outside of key range

### ISSUE THREAD

**Issue by batata004** [FluidSynth/fluidsynth#1250] opened 2023-06-05 22:57 UTC
This bug happens with any soundfont, is very simple to reproduce. Take a look at the screenshot below:

![image](https://github.com/FluidSynth/fluidsynth/assets/8988923/cfb6f3c9-d1a7-4739-ac20-b06441153445)

You can see I didnt specify a "Key range" to "Pad Amb 1" at the `PRESET`. However in the `INSTRUMENTS` panel I specified a "Key range", see print below:

![image](https://github.com/FluidSynth/fluidsynth/assets/8988923/a1a13fe7-01ed-4858-ace0-8f562a098bbd)

When this happens, FluidSynth will not care about the "Key range" specified at the `INSTRUMENTS` panel. I need to explicitly set it ALSO at the PRESET panel. This is bad, because I will have to duplicate some information and keep track of it in at least 2 places.

If I set the "Key range" at the `PRESET` panel, it all works as expected. I am using FluidSynth on Android to test this out, I import the soundfont and start playing it.

**Comment by jjceresa** [comment] 2023-06-06 10:00
Thanks for your clear description which is related first to Polyphone sf2 editor than to fluidsynth . But did you tried another sf2 editor before adding a bug label to fluidsynth ?

**Comment by batata004** [comment] 2023-06-06 14:01
@jjceresa could you please point me to another editor so I can try?

**Comment by derselbst** [comment] 2023-06-06 14:57
https://github.com/FluidSynth/fluidsynth/wiki/SoundFont#soundfont-editors

**Comment by batata004** [comment] 2023-06-07 00:35
Just tried Swami and the problems persists. It surely is a problem with fluidsynth or a bug on both sofwares (swami and poliphone)

**Comment by derselbst** [comment] 2023-06-07 12:37
I quickly tested it and was able to reproduce this behavior. Without having done an in-depth analysis, here's what's happing from my understanding of the SoundFont spec:

The key range of neither of the preset zones is specified. Therefore, according to section `8.1.3 Generator Summary` of the spec, a default range of `0-127` is assumed.

In the next step, the instrument zones are evaluated. In your case, there are two local instrument zones, which do not have a key range specified. Because of that, a default range of `0-127` is assumed and therefore the global instrument zone is never being looked at.

According to my understanding of section `9.4 The SoundFont Generator Model`, this is incorrect, esp. because:

> A generator in a global instrument zone that is identical to a default generator supersedes or replaces the default
generator

Since the local instrument zone's keyrange is not specified, it should fall back to the global instrument zone's key range.

---

@jjceresa Do you agree? Do you currently have some time to do a pull request?

**Comment by batata004** [comment] 2023-06-08 00:08
@derselbst well done, you made a really deep investigation! That's exactly what is going on. Hope some dev find time to solve it! I am very thankfull for this library, it helped me a lot in the music field.

**Comment by jjceresa** [comment] 2023-06-10 07:53
>According to my understanding of section 9.4 The SoundFont Generator Model....

@derselbst, Yes Tom, your understanding of precedence of generators ([local]->[global]->defaut) is right.
The same rule applies at preset and instrument level:
- A global generator (if present) supersedes default generator.
- A local generator(if present) supersede a global or default generator.

I didn't find time before you to do the PR. Sorry

@batata004, Thanks for your welcome report.

**Comment by jjceresa** [comment] 2023-06-10 08:17
@derselbst, In Fix zone range initialization #1251, there a typo mistake in comment src/sfloader/fluid_defsfont.c line 1450
"...However, they should be inited" could be changed to "...However, they should be superseded".

Have a good day.

**Comment by derselbst** [comment] 2023-06-14 11:48
Ok, thanks @jjceresa. I've rephrased the comment to hopefully clarify things. Merged it already, will be part of 2.3.3.

**Closed** 2023-06-14 11:48 UTC
Labels: bug
