### ISSUE TITLE
make install does not completely install components on MacOS

### ISSUE THREAD

**Issue by vlazzarini** [FluidSynth/fluidsynth#1024] opened 2022-01-14 11:19 UTC
### FluidSynth version
FluidSynth runtime version 2.2.4
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.2.4
Sample type=double

### Describe the bug
Installation from sources on MacOS is incomplete. The framework is installed with no headers, so it is impossible to use the API.

### Expected behavior
`make install `  installs all required components. Ideally, headers should be placed inside the framework, but at least they should be installed in a public location (e.g. ${CMAKE_INSTALL_PREFIX}/include). 

### Steps to reproduce
- `make install`
- try to compile a program using the Fluidsynth API.

### Additional context
Flluidsynth is used as a dependency for the Csound plugin fluidOpcodes. Installation worked correctly for 1.x, but not so for 2.2.4. I had to copy the headers by hand, which is not ideal. Note that pointing to use `brew` is not a solution for cases where we want to provide binary packages for users.

**Comment by derselbst** [comment] 2022-01-14 16:38
The respective lines in the build system haven't changed since 11 years. I don't see a reason why this would have worked back then. I don't know about Mac frameworks either.

I added a [make install step into our CI pipeline](https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=6789&view=logs&j=1448839f-898c-5b46-2db8-b1e2e0090bd8&t=bef3fb0f-a5c6-52ae-be7e-0a03e18cc2b6&l=46), but it fails because for some reason CMake doesn't respect the INSTALL_PREFIX when installing the framework. In that state, I cannot even test or verify your observation.

Perhaps @pedrolcl can help out?

**Comment by pedrolcl** [comment] 2022-01-14 17:43
My macbook is out of order since the last upgrade to macOS 10.15, which is the latest that the old machine can accept. Well, in reality Catalina is the latest macOS version that accepts to be installed on my old laptop. So I can't test anything on a real macOS installation at this moment. But I can provide some comments about the current CMake buildsystem (master branch, after the recent CMake modernization).

There are two build variants in FluidSynth's CMake buildsystem, depending on the value of the `enable-framework` option. With this value = on, the build system generates a macOS style framework, which is a  directory with the name "FluidSynth.framework" with the headers inside a directory named `Headers`, which should include the public headers unless something is buggy.  The framework directory itself is installed at the location ${FRAMEWORK_INSTALL_DIR} whose default value is assigned in `cmake_admin/DefaultDirs.cmake`. When the `enable-framework` option is disabled, the build system generates a classic Unix style library which is installed at the location ${CMAKE_INSTALL_LIBDIR} with the headers at ${CMAKE_INSTALL_HEADERS}. 

I've included the mac frameworks option long time ago in the cmake buildsystem, because I though that other mac developers would like to have it, but after some experimentation with it the latest years I've always used the classic Unix library for my own projects. That is exactly what Homebrew does too.

About the CI failure:
~~~
-- Installing: /Library/Frameworks/FluidSynth.framework
CMake Error at src/cmake_install.cmake:72 (file):
  file INSTALL cannot make directory
  "/Library/Frameworks/FluidSynth.framework": Permission denied.
~~~
The error message is quite clear: writting to the system wide `/Library/Frameworks/` location requires admin privileges. You may try to override the default value of `FRAMEWORK_INSTALL_DIR` to some other place. I think that the problem is that  the variable ${CMAKE_INSTALL_PREFIX} is not prepended for some reason to the FRAMEWORK DESTINATION here:
https://github.com/FluidSynth/fluidsynth/blob/711ec9608af4596a9f7ffdc2fab5d2fe41750af9/src/CMakeLists.txt#L403

**Comment by pedrolcl** [comment] 2022-01-14 19:09
I think that the problem with FRAMEWORK_INSTALL_DIR is that it starts with the character '/', indicating an absolute path. Removing that character converts the path in relative, and then the install() macro will prepend the CMAKE_INSTALL_PREFIX. 

Anyway, please test #1027

**Comment by vlazzarini** [comment] 2022-01-14 19:32
Thx for the quick reply. 

The framework is missing the Headers directory, so that's one issue.

Installation location as it is, is not a problem because it goes in the correct place, /Library/Frameworks, although it needs admin permissions (just sudo).

In fact, there is something funny in the new MacOS, which makes locally installed frameworks (in $HOME/Library) not be searched anymore. So it seems ok to go to the root location by default.

The main issue is the headers that need to be copied by hand.

Having the framework is a good idea, as we can then pack it with our binaries (together with glib etc) for distribution.

**Comment by pedrolcl** [comment] 2022-01-14 20:39
It would be helpful if you can test this patch, applied over the v2.2.4 sources. Only the headers inside the framework have changed, that should be copied at build time. The install target will need sudo.

https://github.com/pedrolcl/fluidsynth/commit/db81799.patch

**Comment by derselbst** [comment] 2022-01-14 20:46
Nice spot regarding the starting `/`. Unfortunately, now everything is getting installed below `/usr/local` by default, i.e. if the user hasn't specified the INSTALL_PREFIX.

The headers are being installed now, however, it seems like the folder structure for the header has changed so that now there is an empty `Headers` directory being created:

https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=6807&view=logs&j=872bf439-86bb-5ce5-edcd-c35619d700a0&t=1ada5eef-9da5-5c46-0a91-a34be63f8a23&l=74

**Comment by pedrolcl** [comment] 2022-01-14 21:02
> Nice spot regarding the starting `/`. Unfortunately, now everything is getting installed below `/usr/local` by default, i.e. if the user hasn't specified the INSTALL_PREFIX.

That is the default behavior if the user don't specify CMAKE_INSTALL_PREFIX, it has the default value of "/usr/local". The same happens in Linux. Victor will need to specify CMAKE_INSTALL_PREFIX=/ after this fix is released, if he wants the install location "/Library/Frameworks".
 
> The headers are being installed now, however, it seems like the folder structure for the header has changed so that now there is an empty `Headers` directory being created:

That "FluidSynth.framework/Headers" directory should be a symlink to "FluidSynth.framework/Versions/3/Headers". The other directory symlink should be "FluidSynth.framework/Versions/Current" pointing to "FluidSynth.framework/Versions/3". And finally the file "FluidSynth.framework/FluidSynth" should be a symlink to the file "FluidSynth.framework/Versions/3/FluidSynth" (that is the real binary).

My concern is with the file "FluidSynth.framework/Versions/3/Resources/Info.plist", which is generated by cmake, but probably lacks a lot of necessary metadata.

**Comment by derselbst** [comment] 2022-01-14 21:10
> Victor will need to specify CMAKE_INSTALL_PREFIX=/ after this fix is released

Perhaps we should use `CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT` in combination with `enable-framework` and set the PREFIX to `/` ourself. Would that make sense for MacOS?

> That "FluidSynth.framework/Headers" directory should be a symlink

Ok, I'll check

**Comment by pedrolcl** [comment] 2022-01-14 21:19
> > Victor will need to specify CMAKE_INSTALL_PREFIX=/ after this fix is released
> 
> Perhaps we should use `CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT` in combination with `enable-framework` and set the PREFIX to `/` ourself. Would that make sense for MacOS?

Yes. According to the cmake docs, that would make sense:
https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT.html

Anyway, and as I've said, I don't use the FluidSynth.framework myself anymore.

**Comment by derselbst** [comment] 2022-01-14 21:26
> > That "FluidSynth.framework/Headers" directory should be a symlink
> 
> Ok, I'll check

Confirmed: https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=6821&view=logs&j=872bf439-86bb-5ce5-edcd-c35619d700a0&t=48df834d-43d7-50d0-98e3-db035533be60&l=167

> Yes. According to the cmake docs, that would make sense

Ok, I can prepare a change (unless Victor objects)

**Comment by vlazzarini** [comment] 2022-01-14 21:56
It sounds good to me. Let me know if you want me to clone from git and test.

I was also wondering whether the default should be to enable framework build if you are saying the most common thing is to build a plain lib. 

For me, personally, I think framework makes sense, but not sure whether that's general case.

It might also for you guys if you ever want to do binary releases. You can package the dependencies inside the framework and have an "all in one package". We've been doing that with Csound for the last ten or more years and it seems resilient.

Thx for the help.

**Comment by derselbst** [comment] 2022-01-14 22:13
Oh dear, overriding the INSTALL_PREFIX breaks it elsewhere ofc: https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=6832&view=logs&j=872bf439-86bb-5ce5-edcd-c35619d700a0&t=1ada5eef-9da5-5c46-0a91-a34be63f8a23&l=45

Looks like we need a special FRAMEWORK_PREFIX. Will carry on with this tomorrow. Once the CI build works, I'll ping you Victor so you can test if everything is as expected.

> if you are saying the most common thing is to build a plain lib. Maybe that is what the default should be?

I'm open to change the default in fluidsynth 2.3.0.

**Comment by clanmills** [comment] 2022-01-23 11:06
@derselbst Tom:  I'm having trouble compiling and linking the samples on macOS.  Good News, I believe they built OK in the build directory.  It's building them manually from the terminal that's not working very well.

```
625 rmills@rmillsm1:~/gnu/github/fluidsynth/build $ sudo make install
[ 16%] Built target gentables
[ 93%] Built target libfluidsynth-OBJ
[ 95%] Built target libfluidsynth
[100%] Built target fluidsynth
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/lib/pkgconfig/fluidsynth.pc
-- Up-to-date: /usr/local/lib/cmake/fluidsynth/FluidSynthConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/fluidsynth/FluidSynthConfigVersion.cmake
-- Installing: /usr/local/bin/fluidsynth
-- Up-to-date: /Library/Frameworks/FluidSynth.framework
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Resources
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/Current
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Resources
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Resources/Info.plist
-- Installing: /Library/Frameworks/FluidSynth.framework/Versions/3/FluidSynth
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/FluidSynth
-- Up-to-date: /usr/local/lib/cmake/fluidsynth/FluidSynthTargets.cmake
-- Up-to-date: /usr/local/lib/cmake/fluidsynth/FluidSynthTargets-relwithdebinfo.cmake
-- Up-to-date: /usr/local/share/man/man1/fluidsynth.1
626 rmills@rmillsm1:~/gnu/github/fluidsynth/build $ cd ../doc/examples/
627 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ grep gcc fluidsynth_simple.c 
 *   gcc -g -O -o fluidsynth_simple fluidsynth_simple.c -lfluidsynth
628 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ gcc -g -O -o fluidsynth_simple fluidsynth_simple.c -lfluidsynth
In file included from fluidsynth_simple.c:16:
/usr/local/include/fluidsynth.h:98:10: fatal error: 'fluidsynth/types.h' file not found
#include "fluidsynth/types.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
629 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ ls -l /usr/local/include/flu*
-rw-r--r--  1 root  admin  3566 22 Jan 20:01 /usr/local/include/fluidsynth.h
630 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ 
```

It's all rather spooky.  The include files should be in /usr/local/include/fluidsynth.  The package config magic is also suspect as it doesn't appear to know that it's linking a framework:

```
632 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ grep pkg example.c 
  $ gcc -o example example.c `pkg-config fluidsynth --libs`
633 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ gcc -o example example.c `pkg-config fluidsynth --libs`
In file included from example.c:17:
/usr/local/include/fluidsynth.h:98:10: fatal error: 'fluidsynth/types.h' file not found
#include "fluidsynth/types.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
634 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ pkg-config fluidsynth --libs
-L/usr/local/lib -lfluidsynth
635 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ 
```

I have a MBP with the latest macOS (12.1) and m1/arm64 chip.  I also have an elderly x64 Mac-Mini running Catalina (10.15)

I also notice that the sample programs have no instructions to build on Windows (presumably with Visual Studio, not cygwin and/or mingw).

What do you think?  I'll have time available later this week (Thursday and/or Friday).  Would you like me to work on this?

**Comment by vlazzarini** [comment] 2022-01-23 11:30
To build against the framework you need this:

```
cc -o test fluidsynth_simple.c -F/Library/Frameworks -framework FLuidSynth 
```

**Comment by clanmills** [comment] 2022-01-23 11:41
Thanks you, Victor @vlazzarini I think the linking is correct.  It doesn't compile because the headers aren't in the correct directory:

```
636 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ cc -o test fluidsynth_simple.c -F/Library/Frameworks -framework FLuidSynth
In file included from fluidsynth_simple.c:16:
/usr/local/include/fluidsynth.h:98:10: fatal error: 'fluidsynth/types.h' file not found
#include "fluidsynth/types.h"
         ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/fluidsynth.h:98:10: note: did not find header 'types.h' in framework 'fluidsynth' (loaded from '/Library/Frameworks')
1 error generated.
637 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ 
```
There is some framework related code in fluidsynth.pc 

```
639 rmills@rmillsm1:/usr $ cat /usr/local/lib/pkgconfig/fluidsynth.pc 
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: FluidSynth
Description: Software SoundFont synth
Version: 2.2.4
Requires.private: glib-2.0 gthread-2.0
Libs: -L${libdir} -lfluidsynth
Libs.private: -lm -Wl,-framework,CoreAudio,-framework,AudioUnit -Wl,-framework,CoreMIDI,-framework,CoreServices /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libreadline.tbd
Cflags: -I${includedir}
640 rmills@rmillsm1:/usr $ 
```

So, I'm thinking that there's a whole bag of slightly broken pieces here.  I'm willing to spend a day or two to get to the bottom of this.  I saw a brief discussion about the relative merits of Frameworks vs .dylib (and or .a libraries) and that's relevant.

**Comment by vlazzarini** [comment] 2022-01-23 11:46
You probably do not have the latest code where the framework build has been fixed. I do not see the correct installation messages there. It should be:

```
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/lib64/pkgconfig/fluidsynth.pc
-- Installing: /usr/local/bin/fluidsynth
-- Up-to-date: /Library/Frameworks/FluidSynth.framework
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Resources
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/Current
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Resources
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Resources/Info.plist
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/shell.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/version.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/seq.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/midi.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/seqbind.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/settings.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/event.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/types.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/misc.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/synth.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/gen.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/audio.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/ladspa.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/log.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/voice.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/mod.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth/sfont.h
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Versions/3/Headers/fluidsynth.h
-- Installing: /Library/Frameworks/FluidSynth.framework/Versions/3/FluidSynth
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/Headers
-- Up-to-date: /Library/Frameworks/FluidSynth.framework/FluidSynth
-- Up-to-date: /usr/local/share/man/man1/fluidsynth.1
```

Not sure if this was already merged into master, but I'm building from the branch

```
victor@MU-LAP-7ZM build % git branch
* mac-make-install
  master
```

**Comment by clanmills** [comment] 2022-01-23 11:54
Ah, right.  I cloned master 2022-01-22 about 18:00:00 UTC.  I'll wait for the merge.  Can you update the comments in the sample code prologs?

If you'd like me to test/work on the macOS build (or any platform) please let me know.  I will be happy to contribute.

**Comment by vlazzarini** [comment] 2022-01-23 11:58
also according to earlier comments, if you disable the option `enable-framework`, then the build should install correctly as a normal library with headers in the `include` dir as you were expecting it to be.

**Comment by clanmills** [comment] 2022-01-23 12:31
Thanks, Victor.  Good news and ungood news.  You're right.  That generates a .dylib and life is happiness:

```bash
660 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ grep gcc fluidsynth_simple.c 
 *   gcc -g -O -o fluidsynth_simple fluidsynth_simple.c -lfluidsynth
661 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ gcc -g -O -o fluidsynth_simple fluidsynth_simple.c -lfluidsynth
662 rmills@rmillsm1:~/gnu/github/fluidsynth/doc/examples $ 
```

The ungood news is there's a bug in CMakeList
```bash
668 rmills@rmillsm1:~/gnu/github/fluidsynth/build $ cmake .. -Denable_framework=Off
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
...
  Manually-specified variables were not used by the project:

    enable_framework


-- Build files have been written to: /Users/rmills/gnu/github/fluidsynth/build
669 rmills@rmillsm1:~/gnu/github/fluidsynth/build $ 
```
The value of `${CMAKE_SYSTEM}` on my MBP is `Darwin-21.2.0`

Here's my patch:

```diff
671 rmills@rmillsm1:~/gnu/github/fluidsynth/build $ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e3d21cc5..6df86967 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -104,11 +104,11 @@ if ( CMAKE_SYSTEM MATCHES "Linux" )
     option ( enable-systemd "compile systemd support (if it is available)" on )
 endif ( CMAKE_SYSTEM MATCHES "Linux" )
 
-if ( CMAKE_SYSTEM MATCHES "Darwin" )
+if ( "Darwin" MATCHES ${CMAKE_SYSTEM} )
     option ( enable-coreaudio "compile CoreAudio support (if it is available)" on )
     option ( enable-coremidi "compile CoreMIDI support (if it is available)" on )
     option ( enable-framework "create a Mac OSX style FluidSynth.framework" on )
-endif ( CMAKE_SYSTEM MATCHES "Darwin" )
+endif ()
 
 if ( CMAKE_SYSTEM MATCHES "OS2" )
     option ( enable-dart "compile DART support (if it is available)" on )
672 rmills@rmillsm1:~/gnu/github/fluidsynth/build $ 
```

Victor:  I've recently retired from maintaining Exiv2.  I've seen all these kind of things happen to Exiv2.  I know Tom because he occasionally helps Exiv2.  I'm happy to work on fluidsynth.  

Thank you for working on this amazing project.

**Comment by vlazzarini** [comment] 2022-01-23 12:41
Well, you should thank Tom and the other devs, I'm just a user, but I agreed it's an excellent project.

**Comment by clanmills** [comment] 2022-01-23 12:56
When I discovered fluidsynth yesterday, I emailed Tom to express my appreciation.  I took up the Euphonium three years ago and have a Clavinova which plays the accompaniment for my grade pieces.  I would like to understand midi and that's why I'm interested is fluidsynth.  Exiv2 has been a huge undertaking and I'm happy to be escaping.  Don't want to get too involved with fluidsynth, however happy to encourage others. 

This is excellent technology.

**Comment by derselbst** [comment] 2022-01-23 13:48
Hey guys, there's no need to compile the demo programs manually. You can just run `make demo`. I'll add this to the Mac CI builds to ensure the demos compile well there as well.

And no, the changes of this issue haven't been merged to master yet. I wanted to release 2.2.5 this weekend, let's see if I manage to do that.

**Comment by derselbst** [comment] 2022-01-23 13:53
@clanmills There's a typo in the option you used: It should be `enable-framework` not `enable_framework`

**Comment by clanmills** [comment] 2022-01-23 14:01
@derselbst Wow!  You are right.  I wonder why my patch worked.  Bin my patch.  That's great.  It's building the `.dylib` .  I knew that the code had been successfully built in the build directory.  I was curious about writing/linking my own code.

Apologies for the noise.  Let me keep out of your way.

**Closed** 2022-02-20 17:30 UTC
Labels: bug
