### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by stefan-balke** [FluidSynth/fluidsynth#445] opened 2018-10-15 09:14 UTC
Hi,

I added a `conda-forge` recipe for `fluidsynth`
https://github.com/conda-forge/fluidsynth-feedstock

Especially in scientific environments, this is very handy.

However, I still have a problem on Linux:
https://github.com/conda-forge/fluidsynth-feedstock/issues/1

The build plan is here:
https://github.com/conda-forge/fluidsynth-feedstock/blob/master/recipe/build.sh

Am I missing something?

Thanks
Stefan

**Comment by derselbst** [comment] 2018-10-15 15:37
Everything works as intended. fluidsynth attempts to start an audio
driver. You have only compiled with OSS support, so it starts OSS, but
your system doesnt provide OSS. Make sure you compile with drivers
also supported on your target system, e.g. ALSA.

2018-10-15 11:16 GMT+02:00, Stefan Balke <notifications@github.com>:

**Comment by stefan-balke** [comment] 2018-10-15 15:59
Hey @derselbst,

thanks for the answer.

Shouldn't `ALSA` be enabled by default?
https://github.com/FluidSynth/fluidsynth/blob/master/CMakeLists.txt#L77

Thanks
Stefan

**Comment by derselbst** [comment] 2018-10-15 18:03
The build machine doesnt have the required alsa development files
installed. Make sure they are installed and support will be enabled
automatically during compilation, cf. the cmake build summary.

2018-10-15 18:00 GMT+02:00, Stefan Balke <notifications@github.com>:

**Comment by stefan-balke** [comment] 2018-10-16 09:58
Ah, thanks for the hint.

I see that you install `libasound2-dev`. I have `alsa-lib` which includes that lib. You check for `alsa` in your `cmake` file.
https://github.com/FluidSynth/fluidsynth/blob/master/CMakeLists.txt#L469

However, you just need `libasound2-dev`, wouldn't it be sufficient to check for that then?

**Comment by derselbst** [comment] 2018-10-16 15:48
Ok, your question (and this whole topic) basically tell me that you are very inexperienced in compiling C/C++ programs. You should learn about cmake, pkg-config and most importantly about how _your_ package manager of _your_ distribution treats development files.

This is no support forum, so pls. understand that I'm closing this now.

**Closed by derselbst** 2018-10-16 15:48 UTC

**Comment by stefan-balke** [comment] 2018-10-17 07:59
Yes, you are right and thanks for this enlightening answer. 👎

**Comment by derselbst** [comment] 2018-10-17 14:57
You're welcome. And for even more enlightenment I highly recommend you pay more attention to our [issue template](https://raw.githubusercontent.com/FluidSynth/fluidsynth/master/.github/issue_template.md) next time.

**Comment by stefan-balke** [comment] 2018-10-17 16:51
I highly recommend you to the code of conduct of open source: https://opensource.guide/code-of-conduct/

This is not the way to communicate with other developers. Although C++ is not my home town, I do a lot to make those things more accessible to other users...if you don't care...fine...but your users will..

**Comment by derselbst** [comment] 2018-10-17 18:52
fluidsynth has the clear message: _If you have a question or need support, contact our mailing list._

The mailing list is our community, consisting of many competent and kind users/developers. It's frustrating when people ignore this and bypass the community by opening tickets at Github. Yet, I gave your issue a fair review, concluded that it's not a bug and provided keywords for further information. 

My comment above was neither meant to be offensive nor hostile. If you felt so, I'm sorry.

**Comment by stefan-balke** [comment] 2018-10-17 19:30
Alright, didn‘t know about the mailinglist. Maybe sth. To add to the Readme? Sorry for getting emotional. Let‘s get back to a factual basis. Will post it on the mailinglist. Might be that your cmake file could get a simple update to work in both build systems.
