### ISSUE TITLE
Delay appears after leaving the process running for long enough.

### ISSUE THREAD

**Issue by Zungrysoft** [FluidSynth/fluidsynth#785] opened 2021-03-01 06:13 UTC
### FluidSynth version  
```FluidSynth runtime version 1.1.11
Copyright (C) 2000-2018 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

FluidSynth executable version 1.1.11
Sample type=double
```

### Hardware  
Raspberry pi 3 Model B v1.2

### Describe the bug  
After a certain amount of time (I estimate about five or six hours) of fluidsynth running continuously, notes gain a delay of about one second. The MIDI inputs process immediately and show up in stdout, but the sounds have a delay before playing out of the speakers. The delay is either there or it isn't. It doesn't gradually get more and more delayed. One time, the delay started in the middle of me playing.

The delay is fixed if the fluidsynth process is restarted.

I ran `-free -m` to see if it was a memory leak and this was the output:
```              total        used        free      shared  buff/cache   available
Mem:            924         207         444           6         272         659
Swap:            99           0          99
```

I can provide more system information if requested.

I am using the arachno soundfont, found here: http://www.arachnosoft.com/main/soundfont.php

### Expected behavior  
There should not be a delay.

### Steps to reproduce  
I just leave the process running for a few hours on my raspberry pi. After a long enough time, the delay appears.

**Comment by derselbst** [comment] 2021-03-01 08:36
Please provide the command line that you use to execute fluidsynth. Try using a different audio driver. Also note that `1.1.11` is way outdated and there is no support anymore. Pls. test if can reprocude it with `2.1.7`.

**Comment by jjceresa** [comment] 2021-03-01 12:26
>Raspberry pi 3 Model B v1.2
>After a certain amount of time (I estimate about five or six hours)
>The MIDI inputs process immediately and show up in stdout, but the sounds have a delay before playing out of the speakers. 
>The delay is either there or it isn't.

From your description, this `random delay` occurs as  an audible "latency".
Please, would you also make this try ?: 
- using an `audio file player` (instead of fluidsynth) and
- playing the file continuously (in loop) and
- using the same audio driver.

**Comment by Zungrysoft** [comment] 2021-03-02 05:14
I tried using `apt-get update` and `apt-get upgrade` to install the latest version of fluidsynth, but it doesn't seem to have it. Is it a different package? Or do I need to install it directly from this repo?
```
alt@raspberrypi:~ $ sudo apt list | grep fluidsynth

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

fluidsynth-dssi/stable 1.0.0-6 armhf
fluidsynth/stable,now 1.1.11-1 armhf [installed]
kodi-audiodecoder-fluidsynth-dbg/testing 2.1.0-1~buster armhf
kodi-audiodecoder-fluidsynth/testing 2.1.0-1~buster armhf
libfluidsynth-dev/stable 1.1.11-1 armhf
libfluidsynth1/stable,now 1.1.11-1 armhf [installed,automatic]
tuxguitar-fluidsynth/stable 1.2-23 armhf
vlc-plugin-fluidsynth-dbgsym/testing 3.0.12-0+deb10u1+rpt1 armhf
vlc-plugin-fluidsynth/testing 3.0.12-0+deb10u1+rpt1 armhf
```

For the command, I have it setup to run automatically on login. I followed this video: https://www.youtube.com/watch?v=HMbMyLnL4EQ

This is the .sh file that starts up the program:
```
#!/bin/bash

killall fluidsynth

fluidsynth -si -p "fluid" -C0 -R0 -r48000 -c2 -z1024 -d -f inst/arachno -a alsa -m alsa_seq &

sleep 3

keyboard=$(aconnect -o | grep "Oxygen 49")
mixer=$(aconnect -o | grep "Oxygen 49")

if [[ $keyboard ]]
then
aconnect 'Oxygen 49':0 'fluid':0
echo keyboard connected
fi
if [[ $mixer ]]
then
aconnect 'Oxygen 49':0 'fluid':0
echo mixer connected
fi

exit
```

I am using alsa. What other audio drivers should I try? And how would I need to modify the command to run them?

I am running `speaker-test -c2 -twav` overnight. I'll report back on whether there is a delay between stdout and the audo plauing in the morning.

**Comment by derselbst** [comment] 2021-03-02 16:52
> What other audio drivers should I try?

`jack` would be a good idea.

> And how would I need to modify the command to run them?

https://github.com/FluidSynth/fluidsynth/wiki/UserManual#options

I assume that alsa keeps increasing the latency because underruns occur. So, try playing around with the latency parameters, e.g. `-c4 -z512`. And decrease the sample-rate to e.g. 32kHz, to avoid any potential underrun.

**Comment by Zungrysoft** [comment] 2021-03-03 01:10
I left speaker-test running overnight and no latency appeared.

I don't see how editing the buffer size/count would change the likelihood of underruns. I think I just need to configure alsa to never increase the latency on its own. (If that is what's causing it.) I'll try out your settings though.

I'll also try out jack.

**Comment by Zungrysoft** [comment] 2021-03-03 07:27
With those changed settings, the delay still kicks in. But when it does, the audio also becomes all garbled.

**Comment by jjceresa** [comment] 2021-03-03 17:44
> I think I just need to configure alsa to never increase the latency on its own. (If that is what's causing it.) 

Assuming that alsa increase the latency on its own doesn't explain why alsa does this only 5 hours later. So, if it is possible to configure alsa to never increase the latency, it worth to try this.

Please, for the reasons said by Tom, have a try also using version  2.1.7 compiled from source (using cmake, make, install)
https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake.
Please, also have a try running  fluidsynth yourself on the command line (instead of automatically on login).

>With those changed settings, the delay still kicks in. But when it does, the audio also becomes all garbled.
Which values `x`, `y`, `z` have you really used for -c`x` -z`y` -r`z`  settings ?

**Comment by mawe42** [comment] 2021-03-03 18:55
I have never heard that ALSA could dynamically react to underruns or alter requested buffers and/or latency. Sound servers like Jack and pulseaudio can do that, but not plain ALSA.

@Zungrysoft I assume you are not using the low-quality PWM audio output of the Raspberry but some kind of external sound interface? Can you give us more details on the actual hardware that you use for sound output? And are you sure you are using plain ALSA, or do you have pulseaudio running as well?

**Comment by mawe42** [comment] 2021-03-03 20:12
It could also be your Raspberry PI overheating and going into thermal throttling. Do you have the RPi in an enclosure?
Maybe run the following command once after startup, then again when you notice the extra audio latency after 5-6 hours:
```
vcgencmd get_throttled
```

0x00 means no throttling occured. Other values will indicate some sort of throttling and/or under-voltage event.

**Comment by mawe42** [comment] 2021-03-18 13:33
@Zungrysoft Do you have any more information for us about this problem?

**Comment by derselbst** [comment] 2021-03-27 16:33
I see no evidence that this problem is caused by fluidsynth. Closing.

**Closed by derselbst** 2021-03-27 16:33 UTC
Labels: bug
